import * as Localize from 'react-localization';

export interface ITranscriberStrings extends Localize.LocalizedStringsMethods {
    "accept": string;
    "assigned": string;
    "available": string;
    "bible": string;
    "congratulations": string;
    "continue": string;
    "other": string;
    "review": string;
    "storybook": string;
    "submit": string;
    "test": string;
    "transcribe": string;
    "unassign": string;
    "upload": string;
    "youhavereached": string;
    "inboxzero": string;
    "haveaniceday": string;
    "todo": string;
    "all": string;
    "transcribed": string;
    "reviewed": string;
    "synced": string;
    "logout": string;
};

export interface IUserSettingsStrings extends Localize.LocalizedStringsMethods {
    "chooseAvatar": string;
    "english": string;
    "fastForward": string;
    "font": string;
    "keyboardShortcuts": string;
    "language": string;
    "large": string;
    "medium": string;
    "name": string;
    "password": string;
    "playPause": string;
    "reset": string;
    "reviewComments": string;
    "reviewer": string;
    "rewind": string;
    "role": string;
    "save": string;
    "slowDown": string;
    "small": string;
    "speedUp": string;
    "transcriber": string;
    "user": string;
    "nameErrorMessage": string;
    "fontErrorMessage": string;
    "playPauseErrorMessage": string;
    "rewindErrorMessage": string;
    "fastForwardErrorMessage": string;
    "slowDownErrorMessage": string;
    "speedUpErrorMessage": string;
};

export interface IProjectSettingsStrings extends Localize.LocalizedStringsMethods {
    "next": string;
    "chooseALanguage": string;
    "lookingForProjects": string;
    "selectProject": string;
    "noProjectsFound": string;
    "browseForProject": string;
    "createEmptyProject": string;
    "pairedWithParatextProject": string;
    "projectSettings": string;
    "autoSyncParatext": string;
    "allowClaimUnassignedTasks": string;
    "people": string;
    "tasks": string;
    "addUser": string;
    "addTask": string;
    "addMany": string;
    "sortByRoles": string;
    "sortByType": string;
    "projectName": string;
    "clickToPair": string;
    "taskDetails": string;
    "userDetails": string;
    "delete": string;
    "audioFile": string;
    "reference": string;
    "heading": string;
    "assignedTo": string;
    "roles": string;
    "otherProjects": string;
    "admin": string;
    "reviewer": string;
    "transcriber": string;
    "pairWithParatext": string;
    "referenceFormat": string;
    "skip": string;
    "copyToClipboard": string;
};